name: Migraine Magick™
favicon: null
layout_spectrum: 0.8373441607691348
typography_spectrum: 0.4395342762582004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b7b7b7'
    - '#747474'
    - '#c41f09'
  brandStrength: 0.9457917017862201
  lightness: 0.6338875005021691
  saturation: 0.12769863731227815
  rhythmicContrast: 0.34481462091207504
purpose: []
